#!/usr/bin/env python

'''
(1) Runs a TRF search, (2) soft masks the sequences based on the results, then (3)
runs a sliding-window self-LASTZ search of the soft-masked sequences.

Input:  A set of FASTA sequence files.
Output: A set of BED files indicating possible termini locations. Also,
          sets of BED files showing TRF results and sets of FASTA sequence files
          soft-masked based on TRF results.

Step 1.) Soft mask tandem repeats.

a.) Run TRF.
      - E.g., trf AL_scaffold1.fas 2 7 7 80 10 50 2000 -d -h -m
      - Note: May need to first edit sequence names; e.g., scaffold_1 instead of AL_scaffold1.
b.) Convert TRF DAT file to BED format.
      - E.g., python trf_to_bed.py AL_scaffold1.fas.2.7.7.80.10.50.2000.dat AL_scaffold1-trf.bed
c.) Soft mask.
      - E.g., bedtools maskfasta -soft -fi AL_scaffold1.fas -fo AL_scaffold1-trf.fas -bed AL_scaffold1-trf.bed
      - Note: to validate output, compare to hard mask file generated by TRF (".mask" file, generated using -m option).
      
Step 2.) Run sliding-window self-LASTZ of soft-masked assembly.
    - E.g., ./termini_search.py AL_scaffold1-trf.fas 1>AL_scaffold1-lastz.bed
'''



import argparse
import time
from subprocess import call
import trf_to_bed
import termini_search

def parse_cl():
    parser = argparse.ArgumentParser()
    parser.add_argument('infiles', nargs='+',
                        help='FASTA file(s) to search')
    
    # TO DO
    parser.add_argument('--cpus', type=int, default=4,
                        help='max number of cpus to use')
    
    # trf
    
    parser.add_argument('--max_period', default='2000',
                        help='TRF MaxPeriod argument [default 2000]')
    parser.add_argument('--trf_copies', type=int, default=0,
                        help='Do not mask TRF repeats with fewer than this number of copies [default 0]')
    
    # termini_search 
    parser.add_argument('--max_te_length', type=int, default=50000,
                        help='maximum allowed TE length (bp) [default 50000]')
    parser.add_argument('--window_length', type=int, default=300000,
                        help='window length (bp); should be at least 2x max_te_length [default 300000]')
    parser.add_argument('--format_type', choices=['simple', 'blocks'], default='simple',
                        help='output each terminus as a separate BED line ("simple") or as "blocks" [default "simple"]')
    parser.add_argument('--gap', default='400,30',
                        help='LASTZ gap penalties [default "400,30"]')
    parser.add_argument('--ydrop',
                        help='LASTZ y-drop threshold [default: not set => "open+300extend"?')   # see http://galaxylocal.genenetwork.org:8080/tool_runner?tool_id=lastz_paired_reads_wrapper
    parser.add_argument('--start', type=int, default=0,
                        help='start at this position in the sequence (bp); zero-based indexing [default 0]')
    return parser.parse_args()


if __name__ == '__main__':
    #if 'q' ==raw_input("!! Don't forget to RENAME and UNMASK the sequences before starting, if necessary. ALSO, note that the sequence files must be in (or linked to from) the cwd. (To do: fix this.)" +
    #                    "Enter <q> to quit or any other key to continue." ):
    #    exit(0)
    args = parse_cl()
    for fasta_infile in args.infiles:
        
        time0 = time.time()
        print "\n\n*** Processing file %s ***\n" % fasta_infile
        
        # 1a.) Run TRF.
        call(['trf', fasta_infile, '2', '7', '7', '80', '10', '50', args.max_period, '-d', '-h'])            # e.g., trf AL_scaffold1.fas 2 7 7 80 10 50 2000 -d -h -m
        
        # 1b.) Convert TRF DAT file to BED format.
        trf_outfile = '.'.join([fasta_infile, '2.7.7.80.10.50', args.max_period, 'dat'])                     # e.g., AL_scaffold3-head1000.fas.2.7.7.80.10.50.2000.dat (seems to be hard-coded into TRF, no option to change)
        bed_outfile = fasta_infile + '.trf.bed'
        trf_to_bed.run(trf_outfile, bed_outfile, args.trf_copies)
        
        # 1c.) Soft mask.
        mask_outfile = fasta_infile + '.masked'
        call(['bedtools', 'maskfasta', '-soft', '-fi', fasta_infile, '-fo', mask_outfile, '-bed', bed_outfile]) # e.g., bedtools maskfasta -soft -fi AL_scaffold1.fas -fo AL_scaffold1-trf.fas -bed AL_scaffold1-trf.bed
        
        # 2.) Run sliding-window self-LASTZ of soft-masked assembly.
        cfg = termini_search.Config()
        cfg.infilename = mask_outfile
        cfg.max_te_length = args.max_te_length
        cfg.window_length = args.window_length
        cfg.format_type = args.format_type
        cfg.gap = args.gap
        cfg.ydrop = args.ydrop
        cfg.start = args.start
        termini_search.run(fasta_infile+'.termini_search', cfg)            
        
        print '\n*** Completed processing of file %s in %i seconds. ***\n' % (fasta_infile, time.time()-time0)
