#!/usr/bin/env python

'''
Read in a BED file and return object containing various stats,
including those needed by TE Learn; E.g.,
+ # of each type
+ coverage of each type
+ average length of each type
'''

from __future__ import print_function
import sys
import argparse
from tenames import TeNames

class BedRecord():
    
    def __init__(self, line):
        record = (line.split())[0:5]
        self.scaffold   = record[0]
        self.start      = int(record[1])
        self.end        = int(record[2])
        self.name       = record[3]
        self.score      = float(record[4])
    
    def superfamily(self):
        return TeNames.superfamily_for(self.name)
    
    def len(self):
        return self.end - self.start



class StateStats():
    
    def __init__(self, records):
        self.count = 0.0                                                        # use float to defeat python integer division
        self.totalLen = 0.0
        for r in records:
            self.count += 1
            self.totalLen += r.len()
    
    def avg_len(self):
        return self.totalLen / self.count
    
    def transp_self(self, fragFactor = 1.0):
        return ( self.totalLen - ( self.count / fragFactor ) ) / self.totalLen
    
    def transp_to_bg(self, fragFactor = 1.0):
        return ( self.count / fragFactor ) / self.totalLen



class ScaffoldSizes():
    
    def __init__(self, chromsizes):
        self.sizes = {}
        self.numScaffolds = 0.0
        self.genomeSize = 0.0
        for line in chromsizes:
            fields = line.split()
            if len(fields) != 2:
                raise Exception("Unexpected chrom.sizes record: " + line)
            size = int(fields[1])
            self.sizes[fields[0]] = size
            self.genomeSize += size
            self.numScaffolds += 1



class BedStats():
    
    def __init__(self, bedfile, chromsizes, bgState):
        self.bgState = bgState
        self.scafSizes = ScaffoldSizes(chromsizes)
        self.records = {}
        self.stateStats = {}
        self.nRecords = 0
        self.recordsLen = 0                                                       # assumes no overlaps
        self._load(bedfile)
        self._calc()

    def _load(self, bedfile):
        for line in bedfile:
            if '#' == line[0]:                                                  # skip comment lines
                continue
            self._add(BedRecord(line))
    
    def _add(self, bedRecord):
        if bedRecord.scaffold not in self.scafSizes.sizes:
            raise Exception('scaffold ' + bedRecord.scaffold + ' not in chrom.sizes')
        state = bedRecord.superfamily()                                   
        if state not in self.records:
            self.records[state] = []
        self.records[state].append(bedRecord)
    
    def _calc(self):
        for state in self.records:
            stateStats = StateStats(self.records[state])
            self.stateStats[state] = stateStats
            self.nRecords += stateStats.count
            self.recordsLen += stateStats.totalLen
        if self.bgState in self.stateStats:
            raise Exception('Cannot initialize background to ' + bgState + ' because it already exists.')
        bgStats = StateStats([])
        bgStats.count = self.nRecords + 2 * self.scafSizes.numScaffolds         # assumes gap between each record and at start and end of each scaffold
        bgStats.totalLen = self.scafSizes.genomeSize - self.recordsLen
        self.stateStats[self.bgState] = bgStats
    
    def states(self):
        return self.stateStats.keys()
    
    def transp_from_bg(self, state, fragFactor = 1.0):
        if state == self.bgState:
            raise Exception('transp_from_bg() cannot be called for background state')
        return ( self.stateStats[state].count / fragFactor ) / self.stateStats[self.bgState].totalLen
    
    def statep(self, state, fudge = 0.0):
        x = self.stateStats[state].totalLen / self.scafSizes.genomeSize
        return x + (1-x)*fudge



def parse_cl():
    parser = argparse.ArgumentParser()
    parser.add_argument('bedfile', type=argparse.FileType('r'),
        help='BED input file')
    parser.add_argument('chromsizes', type=argparse.FileType('r'),
        help='chromosome sizes in a tab-separated file such as that generated by fetchChromSizes '
             '(see https://genome.ucsc.edu/goldenPath/help/bigBed.html)' )
    parser.add_argument('--background', type=str, default='None',
        help='Name of background state (i.e. what to call gaps) [default: \'None\']')
    return parser.parse_args()

if __name__ == '__main__':
    args = parse_cl()
    stateStats = BedStats(args.bedfile, args.chromsizes, args.background, )
    print(stateStats)